#!/bin/sh

set -e

clang-format -i Source/*.m Source/*.h

rm -rf "Build"
mkdir -p "Build/Drawing Benchmark.app/Contents"
mkdir -p "Build/Drawing Benchmark.app/Contents/MacOS"
mkdir -p "Build/Drawing Benchmark.app/Contents/Resources/en.lproj"

cat Source/*.h Source/*.m > "Build/Drawing Benchmark.app/Contents/Resources/Text.txt"

plutil \
	-convert binary1 \
	-o "Build/Drawing Benchmark.app/Contents/Info.plist" \
	"Data/Info.json"

plutil -convert binary1 \
	-o "Build/Drawing Benchmark.app/Contents/Resources/en.lproj/InfoPlist.strings" \
	"Data/InfoPlist.json"

clang \
	-fmodules -fobjc-arc \
	-g \
	-fsanitize=undefined \
	-W \
	-Wall \
	-Wextra \
	-Wpedantic \
	-Wconversion \
	-Wimplicit-fallthrough \
	-Wmissing-prototypes \
	-Wshadow \
	-Wstrict-prototypes \
	-o "Build/Drawing Benchmark.app/Contents/MacOS/Drawing Benchmark" \
	"Source/EntryPoint.m"

plutil \
	-convert xml1 \
	-o "Build/Drawing Benchmark.entitlements" \
	"Data/Entitlements.json"

plutil \
	-insert "com\.apple\.security\.get-task-allow" -bool YES \
	"Build/Drawing Benchmark.entitlements"

codesign \
	--sign - \
	--entitlements "Build/Drawing Benchmark.entitlements" \
	--options runtime "Build/Drawing Benchmark.app/Contents/MacOS/Drawing Benchmark"
